language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t whoopinstick/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true whoopinstick/udemy-docker-react npm run test -- --coverage
